database:
  host: 69.62.75.204
  port: 5432
  user: admin
  password: root
  dbname: appdb
  sslmode: disable
redis:
  host: 69.62.75.204
  PORT: 6379
  db: 0

jwt:
  secret: your-super-secret-jwt-key
  expiry_hour: 24

server:
  port: 8080
  host: localhost
