database:
  host: 69.62.75.204
  port: 5432
  user: user
  password: pass
  dbname: test
  sslmode: disable

redis:
  host: 69.62.75.204
  PORT: 6379
  db: 0

s3:
  endpoint: 69.62.75.204:9000
  access_key: admin
  secret_key: password123
  bucket_name: rival-bucket
  sslmode: false

mail:
  smtp_server: 69.62.75.204
  smtp_port: 1025
  web_ui_port: 8025

tb:
  addr: 69.62.75.204:3000

jwt:
  secret: your-super-secret-jwt-key
  expiry_hour: 24

server:
  port: 8080
  host: 69.62.75.204
payment_gateway:
  base_url: https://api.razorpay.com/v1
  api_key: your-razorpay-api-key
